### ISSUE TITLE
mgncs里面的输入法不能用吗？

### ISSUE THREAD

**Issue by incity** [VincentWei/mgncs#3]
我阅读了mgncs里面的ime模块，并未看到有实现键盘绘制的相关代码。
请问下，mgncs里面的输入法如何使用？？

**Comment by VincentWei** [comment]
The code in mgncs for ime is the input engines, not the implementation of input method.

Please fetch mg-demos repository and see the demo `kbd-input`. This demo implements a soft keyboard input method window with a English input method engine and a Chinese Pinyin input method engine.

**Comment by incity** [comment]
thanks for your reply.
but im curious about their relationship? why did u need the ime in mgncs?
