### ISSUE TITLE
Can I have a sample of custom button in Chapter 3 of Part 3 of mgncs_guide

### ISSUE THREAD

**Issue by CaoZewei** [VincentWei/mgncs#8]
I'm a beginner in mgncs. And sorry, I'm too stupid to write my own custom buttons based on the contents of the book，Also,I can't find any sample in mgncs/samples/src/.
So,I want to ask you for a sample about this，Could you provide it？

**Comment by VincentWei** [comment]
We have moved the samples to mg-samples repo:

https://github.com/VincentWei/mg-samples/

in `mgncs/` directory.
